### ISSUE TITLE
 test results about the video 

### ISSUE THREAD

**Issue by zrqi** [1adrianb/face-alignment#101]
Hi,Adrian,in your github's home page provides real-time video aligning results, and I wonder how it's done, and the results provided in the test code are about the positioning coordinates of each frame of the video, how do you convert it into the video after the aligning?

**Comment by 1adrianb** [comment]
Hi @zrqi, in the particular example I have run a face detecor on the first frame and then intialised the next one based on the the previous fitting. This tends to work if there is no occlusion, however in general I recommend running a face detector on each frame. The output points are already aligned with the frames. I plotted the points in python, saved them as images and then merged them in a video.
