### ISSUE TITLE
About downloading the face detection CNN

### ISSUE THREAD

**Issue by Peter-beeler** [1adrianb/face-alignment#104]
I have never installed a face detection CNN before, so I run the code given in the ReadMe, the program shows that "Downloading the face detection CNN. Please wait...". However, the program was just stuck here(I'm sure my wifi works well). 
It seems that the CNN is downloaded from your website, I can visit your website in a browser. 
So, what can be the problem? Thanks.
@1adrianb

**Comment by 1adrianb** [comment]
Hi @Peter-beeler ,

I am sorry for this, could you please try downloading it manually and copy it to the expected location? 
You can find the link  and the expected location for it here: https://github.com/1adrianb/face-alignment/blob/3750f83b4d7bf3f4ba6318e40a4292e1aeb241a4/face_alignment/detection/sfd/sfd_detector.py#L38

Let me know if it works.
