### ISSUE TITLE
where to put the pre-trained model to make the detecte code work

### ISSUE THREAD

**Issue by zeagle01** [1adrianb/face-alignment#11]
I had dowloaded the 4 pretrained model(2dfan,3dfan,2dto3d,3d depth),but I don't know where I should put them so the detect code would work.
I ran the detect code under the example fold without pretrained model,turned out that it'll automaticlly downloads the model accordingly,but I couldn't find where the model is

**Comment by 1adrianb** [comment]
First, the torch and pytorch models you downloaded are not compatible so no matter were you place them they won't do anything with this code.
Second, where did you find in the instruction that you need to download the code? Please, just follow them.
Third, the models are downloaded automatically when needed and placed in the home folder.

**Comment by zeagle01** [comment]
thank you for your reply!
so the four pretrained model aren't what I thought they were(which I thought are pretrained models), but what are they? or can you refer me to some link or something?(I had read your paper)
about the second point ,it's a misunderstanding,like you said it's dowloaded automatically. The problem is I don't know where to find the dowloaded model(I can't find them  in my home folder)
finally I tested some images of my own(large pose) with the detect code in examples folder,the results seem ok to me, 3d landmarks, pretty cool!

**Comment by 1adrianb** [comment]
I didn't say that the are not pretrained models, of course they are :) However you took the link from another repository (this one https://github.com/1adrianb/2D-and-3D-face-alignment) and they are NOT compatible. The pretrained models that you downloaded are for Torch7 (implemented in the lua programming language). If you want to use that models, please use them with the code from here: https://github.com/1adrianb/2D-and-3D-face-alignment not with the python one.

They are in the home folder they are just "hidden".  Check this function https://github.com/1adrianb/face-alignment/blob/79878d6232ef79cde9cfb8ac396d42c346e2e61e/face_alignment/utils.py#L140 for an exact location.

**Comment by zeagle01** [comment]
thank you for your reply!
yeah, I checked the function at utils.py and  found the automaticlly dowloaded model at ~/.face_alignment/
