### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'enable_cuda'

### ISSUE THREAD

**Issue by shliang0603** [1adrianb/face-alignment#113]
@1adrianb My environment is Pytorch 0.4.0 and I installed enable cuda env.
![image](https://user-images.githubusercontent.com/37186266/48750853-4b87d500-ecbc-11e8-9b03-834edd00a230.png)

When I modified the parameter，the error is following
![image](https://user-images.githubusercontent.com/37186266/48750928-af120280-ecbc-11e8-91bd-59e726222f5e.png)
![image](https://user-images.githubusercontent.com/37186266/48750955-e1bbfb00-ecbc-11e8-93dd-d2f07e255afb.png)
Can you give me advice ,thanks

**Comment by 1adrianb** [comment]
Hi @shliang0603 as you can see in the last error message you attempt o use 'cuda' without compiling pytorch with cuda support. You can either do that ore use device='cpu' and run it on the cpu, but this will be much slower.
