### ISSUE TITLE
How to install it without pytorch required? 

### ISSUE THREAD

**Issue by monabiyan** [1adrianb/face-alignment#12]
Hi
I am having a lot of difficulties installing pytorch. I was wondering if I can run the example code (detect_landmarks_in_image.py) you provided without installing pytorch and just use cpu?

Thank you so much
Mohsen

**Comment by 1adrianb** [comment]
Hi @monabiyan,
Thanks a lot for your interest. Pytorch doesn't require a GPU and  can be used in CPU mode alone. The most troublesome way to install it is by using conda. Please go to http://pytorch.org/ and pick the package that you like and chose the option "None" for CUDA which will install a CPU-only version.
Unfortunatelly it is not possible to remove pytorch as a depency for now. 
Again please follow the above link and install pytorch in a conda environment. If you still have issues  please let me know or raise a issue with the pytorch team.

**Comment by monabiyan** [comment]
Wow, that was very easy and it works, Thank you @1adrianb
