### ISSUE TITLE
Can I get the head pose from 3d landmarks directly?

### ISSUE THREAD

**Issue by junedgar** [1adrianb/face-alignment#120]
Thank you for your great work!
Can I compute the yaw, pitch and roll from 3D landmarks?
Can you give me some advices?

**Comment by ajayempty** [comment]
Awaiting answer on this...?

**Comment by Alloshee** [comment]
i would like to know the answer

**Comment by zalo** [comment]
Here's a quick example showing how to construct a rotation matrix using the 3D landmarks.   Convert that to pitch/yaw/roll however you like.

https://gist.github.com/zalo/71fbd5dbfe23cb46406d211b84be9f7e
![image](https://user-images.githubusercontent.com/174475/58765561-168cf280-8529-11e9-98fe-8fc9e2e07f0c.png)

**Comment by zhangluustb** [comment]
How about the 2d landmarks only?
