### ISSUE TITLE
Base Part

### ISSUE THREAD

**Issue by PhotonChow** [1adrianb/face-alignment#129]
Sorry, but I wonder what's the function of the base part. It decrease the size of the original inputs without upsampling at the end. Then how to calculate the outputs with the ground truth heatmaps?

**Comment by 1adrianb** [comment]
Sorry for delay, I will assume that you probably sorted it out, but for reference the heatmaps are at resolution 4x smaller than that of the input. The ground truth heatmaps are simply generated at the desired resolution, in this case 64x64px.
