### ISSUE TITLE
Dockerfile is missing boost libs, CMake fails in docker build.

### ISSUE THREAD

**Issue by tetelman** [1adrianb/face-alignment#13]
Only errors shown below.

$docker build -t face-alignment .
...
-- Could NOT find Boost
...
Failed building wheel for dlib
...
Command "/opt/conda/envs/pytorch-py35/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7xmab85s/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lxb8brpv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7xmab85s/dlib/
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

**Comment by 1adrianb** [comment]
Thanks for spotting this @tetelman  The boost part should be now fixed. If you encounter any other issue feel free to open a bug, or even better to make a pull request.
