### ISSUE TITLE
Caffe Model Conversion 

### ISSUE THREAD

**Issue by trohit920** [1adrianb/face-alignment#132]
Hello, I have a simple question. I successfully downloaded the Pytorch model weights. I have to use OpenCV Dnn Module for Face Alignment in my application for which i am planning to use your trained models. But opencv doesn't support the Pytorch as of now. So I am wondering is there any way to convert these weights to caffe model or have you trained any caffe model for this purpose? Any help or advice will be highly appreciated. Thanks in advance.

**Comment by 1adrianb** [comment]
Hi @trohit920,

Unfortunately I don't have them in this format. You can try one of the converters available on github, for example: https://github.com/MTlab/onnx2caffe that converts them via onnx.

**Comment by trohit920** [comment]
@1adrianb Isn't .onnx and .pth model different ? The link you shared convert the .onnx model files to caffe model not .pth models. Am i doing something wrong in here.

**Comment by 1adrianb** [comment]
Pytorch can directly convert pytorch models to onnx, see the pytorch jit module please.
