### ISSUE TITLE
Can I use the " face_alignment " package to turn a profile face image into a front face？

### ISSUE THREAD

**Issue by CXiaoDing** [1adrianb/face-alignment#135]
I run the example——detect_landmarks_in_image.py, and I can get the face landmarks of a profile face image, but I want to get the front face image. Can I get it by using these landmarks? Thank you !!!
@1adrianb @xerus @jeongyoonlee @ashafaei @mihanlg

**Comment by zalo** [comment]
Here's a quickie example for extracting Face Chips using this and OpenCV.

https://gist.github.com/zalo/fa4396ae7a72b7683888fd9cd1c6d920
![image](https://user-images.githubusercontent.com/174475/58766332-20ffba00-8532-11e9-8c11-0b1d58f9b795.png)

**Comment by CXiaoDing** [comment]
@zalo thank you very much!
But I run the example in https://gist.github.com/zalo/fa4396ae7a72b7683888fd9cd1c6d920
and I found if the raw image is profile face, the result is also a profile face image.
Is there any way to change a profile face to a frontal face? 
thank you!

**Comment by c1a1o1** [comment]
@zalo  I  can't open https://gist.github.com/zalo/fa4396ae7a72b7683888fd9cd1c6d920  ????

**Comment by xiao-keeplearning** [comment]
> @zalo 我无法打开https://gist.github.com/zalo/fa4396ae7a72b7683888fd9cd1c6d920 ????
You may need proxy

**Comment by EricHallahan** [comment]
> Is there any way to change a profile face to a frontal face?

No.
