### ISSUE TITLE
What is input and output of depth network?

### ISSUE THREAD

**Issue by mrgloom** [1adrianb/face-alignment#138]
What is input and output of depth network?

https://github.com/1adrianb/face-alignment/blob/87a496b158ff9a215aa6f48262f4e13d8e6c4dd7/face_alignment/api.py#L49

**Comment by 1adrianb** [comment]
The input is the RGB image stacked alongside the previously produced heatmaps.

**Comment by mrgloom** [comment]
And what is output?
Is it just 68 landmark heatmaps? i.e. it don't predict depthmap? i.e. like https://github.com/AaronJackson/vrn
https://github.com/1adrianb/face-alignment/blob/f0cf27cf7c9141f567e135c21495702cdf0aefe3/face_alignment/models.py#L219

**Comment by 1adrianb** [comment]
Aaron's work predict a 3D voxelized volume (DxHxW). This network outputs 68 points, each containing the depth at a given location (x,y).
