### ISSUE TITLE
Re-enable autograd after reading model

### ISSUE THREAD

**Issue by cplusx** [1adrianb/face-alignment#140]
I found when import `face_alignment` package, it set `torch.set_grad_enabled(False)`, which makes torch close autograd. I was planning to use this package to extract landmarks for my training task and it created some trouble because autograd was closed. I spent some time to finally figure this out. 
I think it will be a good feature if autograd is re-enabled after loading model.

**Comment by 1adrianb** [comment]
Thanks for suggestion, I will wrap in torch.no_grad() and fix this.
