### ISSUE TITLE
Can't download, www.adrianbulat.com down

### ISSUE THREAD

**Issue by jakezhaojb** [1adrianb/face-alignment#148]

**Comment by linghai06** [comment]
save problem here. could not reach the download link neither

**Comment by yaSh1thram** [comment]
Yea i am also facing the same problem

**Comment by Songluchuan** [comment]
same problem

**Comment by 1adrianb** [comment]
Sorry everyone, the hosting provider experienced some degraded network performance. The issues should now be addressed. If you still experience problems, please let me know.
