### ISSUE TITLE
bounding box format to be passed

### ISSUE THREAD

**Issue by Reddyforcode** [1adrianb/face-alignment#149]
`preds = fa.get_landmarks(input_img, detected_faces)[-1]`
the detected_faces in wich format should be passed?

**Comment by 1adrianb** [comment]
[ [x1, y1, x2, y2],  ...]  (x1,y1) and (x2,y2) represent the top-left and bottom-right corners of the bbox. If None is passed the code will run one of the included detectors SFD or dlib.

**Comment by Reddyforcode** [comment]
Thanks!

**Comment by mrgloom** [comment]
Also with score?
https://github.com/1adrianb/face-alignment/blob/master/face_alignment/detection/sfd/detect.py#L51
