### ISSUE TITLE
pytorch function should be followed by '_' or not ? in function get_preds_fromhm

### ISSUE THREAD

**Issue by huqiaoping** [1adrianb/face-alignment#15]
Please notice function get_preds_fromhm in face_aligment/utils.py

line 112: `preds[..., 1].add_(-1).div_(hm.size(2)).floor().add_(1)`
I think it should be` preds[..., 1].add_(-1).div_(hm.size(2)).floor_().add_(1)`, otherwise the results will be qual to  `preds[..., 1].add_(-1).div_(hm.size(2))`

line 124: `preds[i, j].add(diff.sign().mul(.25))`
I think it should be `preds[i, j].add_(diff.sign().mul(.25))`, otherwise these two loops always do nothing to the results.

In pytorch, with function followed by  '\_', it will change value of variables, but for function without a '\_', it won't change the value of variabels. for example, function  floor() is defferent from floor_().

@1adrianb

**Comment by 1adrianb** [comment]
Hi @huqiaoping  you are right. I was not very careful I guess and omitted the ``_``.  Feel free to make a pull request, if not I will fix it later on.
Thanks a for catching it!

**Comment by huqiaoping** [comment]
Thanks, this is my first time to make a pull request on github. So happy~
