### ISSUE TITLE
How to infer the the variable 'preds'

### ISSUE THREAD

**Issue by jug971990** [1adrianb/face-alignment#151]
I see that it is a (68,3) numpy array. I am interested in the landmarks for the eyes. From the numpy array I am not able to infer which of those values are related to eye. Please help at the earliest possible. I am in need of this data for my PhD research

**Comment by Reddyforcode** [comment]
i will send you the image with the number of the points in the pred array email me aaabeeelooon@gmail.com

**Comment by Reddyforcode** [comment]
![out](https://user-images.githubusercontent.com/20909101/64643794-314fec80-d3df-11e9-9215-c1b73d28abc9.jpg)
 here you have, the number represent the index in the pred array
