### ISSUE TITLE
How can you get a confidence value out of the heatmaps?

### ISSUE THREAD

**Issue by analogously** [1adrianb/face-alignment#152]
Hi! I believe you can obtain a confidence value for the keypoints out of the heatmap value, but the inner code for heatmaps in get_preds_fromhm is dark, and I can't find any good explanation on how this works, might someone please explain? 
Thank you,
Ana

**Comment by 1adrianb** [comment]
Hi @analogously,
Typically the confidence corresponds to the value of the peak. get_preds_fromhm simple takes the location at the max, applies some heuristics to improve the accuracy and maps the points back to the image space. If you also want the confidence you can simply return also the value of the max.

**Comment by analogously** [comment]
Thank you! What a fast answer! I didn't know how the heatmap tensor was structured but I didn't need to know it because you already obtained the max.
Keep up all that cool research :)
Ana
