### ISSUE TITLE
[Multiple landmarks for image with 2-3 faces]

### ISSUE THREAD

**Issue by vinayak618** [1adrianb/face-alignment#156]
Hi @1adrianb .
How to get the multiple landmark predictions for the image with 2-3 faces in it, and how it chooses just single face from all detected faces after 'sfd' to get the landmarks?
Like the below output:
![test](https://user-images.githubusercontent.com/29506542/65324071-b9e14080-dbc8-11e9-8137-70d6134c0a0d.png)

**Comment by 1adrianb** [comment]
It should already work for multiple faces. Can you please check how many faces did sfd detect? (https://github.com/1adrianb/face-alignment/blob/6a7731168dbb1a15f9ecd5fe4c79c992f179a622/face_alignment/api.py#L140)

**Comment by vinayak618** [comment]
It's detecting all the faces in the image, but it will end putting the landmarks for last face maybe it's just the landmarks is not getting appended for all the face predictions.

**Comment by 1adrianb** [comment]
thanks, I will have a look and fix this towards the end of this week, sorry for the delay
