### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'no_grad'

### ISSUE THREAD

**Issue by ariagecheney** [1adrianb/face-alignment#157]
hello,i use "conda install " to complete your face-alignment,but when i  import face_alignment,i get such a error,  each version will be shown.

(py36)  ✘ chy@chy-PC  ~  conda list | grep pytorch
pytorch                   0.1.12          py36cuda8.0cudnn6.0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
(py36)  chy@chy-PC  ~  conda list | grep cudas  
(py36)  ✘ chy@chy-PC  ~  conda list | grep cuda 
cudatoolkit               8.0                           3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cudnn                     6.0.21                cuda8.0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
nccl                      1.3.4                 cuda8.0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pytorch                   0.1.12          py36cuda8.0cudnn6.0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
(py36)  chy@chy-PC  ~  conda list | grep torh
(py36)  ✘ chy@chy-PC  ~  conda list | grep torch
pytorch                   0.1.12          py36cuda8.0cudnn6.0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**Comment by 1adrianb** [comment]
@ariagecheney please update to pytorch 1.2
