### ISSUE TITLE
Cannot Run with CPU

### ISSUE THREAD

**Issue by lz2470** [1adrianb/face-alignment#158]
Hi, I installed your project via conda. It works fine with gpu, but when I set device='cpu'. Program crashed and report Illegal instruction (core dumped). Please Help~~~ Thanks in Advance.

**Comment by 1adrianb** [comment]
Beyond making sure that you have the latest PyTorch version and that you are using SFD for face detection I am afraid I cannot be more helpful without a full stack trace of the crash.

**Comment by lz2470** [comment]
Hi， " Illegal instruction " is all I got even when I turned on verbose.

**Comment by 1adrianb** [comment]
@lz2470 most likely its due to this: https://github.com/pytorch/pytorch/issues/2714
