### ISSUE TITLE
about pytorch framework you used

### ISSUE THREAD

**Issue by amrabhiagni** [1adrianb/face-alignment#159]
hi, 
I just want to know that why **you haven't written your own code instead of using pytorch framework** for creating model.
**Is it worth to write the code for cnn without using any pytorch like framework ?** 
did you modify any pytorch library in order to complete project ?
just creating layer or create model using pytorch , **is it research** ?

**Comment by 1adrianb** [comment]
Hi @amrabhiagni,
The code implements the method from the following paper using pytorch:
http://openaccess.thecvf.com/content_ICCV_2017/papers/Bulat_How_Far_Are_ICCV_2017_paper.pdf

I am afraid that the rest of your question are quite subjective. I suggest to ask them on reddit/forum instead where I am sure you will get some general impressions regarding them.
