### ISSUE TITLE
Normalizing faces

### ISSUE THREAD

**Issue by dsoprea** [1adrianb/face-alignment#160]
It seems like we can crop faces here, but that the total purpose of this project is to detect faces rather than to actually align them. Are we aware of any other projects out there that go the last mile and use the result of this project to then crop/rotate/tilt/stretch the face to a canonical position and pose which can then be used for training in another network?

**Comment by weltonrodrigo** [comment]
@dsoprea maybe you shorts take a look at DeepFace Lab. They use face landmarks to crop faces.
