### ISSUE TITLE
CUDA error Out of memory 

### ISSUE THREAD

**Issue by mia-minyoung** [1adrianb/face-alignment#166]
Thank you for the great work first! 
But is there anyone who struggles Out of memory issues to get 3D landmark?
I'm using three Geforce TitanX 12Gb in a server and allocating networks in different GPUs respectively.
However, there is still a memory error. Please let me know how you all handle this! 

Thank you for in advanced

**Comment by charlescatta** [comment]
Downsize your input image !

ex:
`
from skimage.transform import resize

img = resize(img, (img.shape[0] // 4, img.shape[1] // 4), anti_aliasing=True)
`
