### ISSUE TITLE
low performance in Jetson nano

### ISSUE THREAD

**Issue by SaddamBInSyed** [1adrianb/face-alignment#167]
Hi 

thanks for your work.

I tested with jetson nano board.
but the fps was very low.

is there any tuning needed to improve the same?

please advise

**Comment by 1adrianb** [comment]
I am afraid I don't have access on a jetson board, but this is to be expected. 
Without retraining the network the simplest thing that you can do is to check which component is the slowest (face detection or keypoints localisation). Then, based on this adjust the resolution of the image, avoid running the detector on each frame, or replace it with  a faster one.
The other more involved options will require retraining the model using fewer stacks and fp16 or int8 precision.
