### ISSUE TITLE
Detector fails for this image

### ISSUE THREAD

**Issue by weltonrodrigo** [1adrianb/face-alignment#169]
https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gettyimages-840637904-1537901994.jpg

Detector fails for this image. It work if the image is resized.

**Comment by 1adrianb** [comment]
@weltonrodrigo The variant of the s3fd included is not run across multiple scales as such very large images may have their faces omitted.  Furthermore this may also lead to an out of memory error. As an workaround you can either (1) resize the image, (2) detect the faces offline and just pass their location or (3) incorporate a better/faster face detection method.

**Comment by weltonrodrigo** [comment]
Changed the title just for the sake of google.

**Comment by eyaler** [comment]
can you give some thumb rules for acceptable image sizes?

**Comment by livefire2015** [comment]
> can you give some thumb rules for acceptable image sizes?

Just from my test: image sizes no bigger than 256x256 px work fine.
