### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ihorbond** [1adrianb/face-alignment#170]
Hi I'm new to python. I tried to install this package with different python versions from 3.5 to the latest 3.8.2 but I keep getting same error when it tries to install pytorch: 

Running setup.py install for torch: started
    Running setup.py install for torch: finished with status 'error'
No module named 'tools.nnwrap'. 

Has anyone ran across this issue ? OS is Windows 10

**Comment by 1adrianb** [comment]
Hi @ihorbond this is an issue with the torch installation not this package in particular.
Please see:
https://stackoverflow.com/questions/56859803/modulenotfounderror-no-module-named-tools-nnwrap
or
https://github.com/pytorch/pytorch/issues/34612

The last one in particular suggests that this is a windows specific issue and suggests an workaround.

**Comment by ihorbond** [comment]
Yes, I'm aware it's not this package's problem and did see that SO post. I was just looking for some guidance on how to make it work. Since I successfully installed torch separately should I comment out the torch requirement in setup.py ?

**Comment by 1adrianb** [comment]
If you installed it already, then yes, removing it from the requirements and installing it from the git repo directly should work.

**Comment by ihorbond** [comment]
Thank you. Few more hoops with opencv errors and C++ build tools missing and I'm done haha
