### ISSUE TITLE
Downloading the face detection CNN. Please wait...

### ISSUE THREAD

**Issue by huangyanting** [1adrianb/face-alignment#171]
![image](https://user-images.githubusercontent.com/37578776/80303425-cc68cb80-87e2-11ea-94da-e2031f0ee3f3.png)
import face_alignment
from skimage import io

fa = face_alignment.FaceAlignment(landmarks_type=face_alignment.LandmarksType._2D, flip_input=False)

input = io.imread('data/14.jpg')
preds = fa.get_landmarks(input)

but i get eroor:
Downloading the face detection CNN. Please wait...

**Comment by 1adrianb** [comment]
Please see https://github.com/1adrianb/face-alignment/issues/155
