### ISSUE TITLE
imagecodecs openjpeg.h: No such file or directory

### ISSUE THREAD

**Issue by gerrito333** [1adrianb/face-alignment#172]
When I run pip3 install face-alignment I get the following error:

    imagecodecs/_jpeg2k.c:602:10: fatal error: openjpeg.h: No such file or directory
     #include "openjpeg.h"
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
    Failed building wheel for imagecodecs

**Comment by 1adrianb** [comment]
If you are on ubuntu try running ```sudo apt-get install -y libopenjpeg-dev``` beforehand.

**Comment by gerrito333** [comment]
Thanks for your prompt reply. Tried, but I am unable to find this package:

apt-get install -y libopenjpeg-dev
E: Unable to locate package libopenjpeg-dev

**Comment by 1adrianb** [comment]
Try installing then ```libopenjp2-7-dev``` please

**Comment by gerrito333** [comment]
With libopenjpeg-dev installed, I still get this message:

    imagecodecs/_jpeg2k.c:602:10: fatal error: openjpeg.h: No such file or directory
     #include "openjpeg.h"
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by 1adrianb** [comment]
That shouldn't be a problem to be honest. Try to see if you can locate where the header is and manually add if its necessary. For an example see https://github.com/python-pillow/Pillow/issues/2387#issuecomment-276072748

**Comment by gerrito333** [comment]
Using a ubuntu18.04 with libopenjpeg-dev and other libs mentioned on https://pypi.org/project/imagecodecs/ solved it. Thanks Adrian for you support.
