### ISSUE TITLE
Where are models' files stored?

### ISSUE THREAD

**Issue by guillermoim** [1adrianb/face-alignment#174]
Hi Adrian, I got a server to which I can only access remotely and the server itself cannot communicate with the Internet to download files. Where exactly does your library store the models (fin my case, for 2d landmarks detections) so I can place them in my server folder? Thanks!

**Comment by borgiaE** [comment]
models_urls = {
    '2DFAN-4': 'https://www.adrianbulat.com/downloads/python-fan/2DFAN4-11f355bf06.pth.tar',
    '3DFAN-4': 'https://www.adrianbulat.com/downloads/python-fan/3DFAN4-7835d9f11d.pth.tar',
    'depth': 'https://www.adrianbulat.com/downloads/python-fan/depth-2a464da4ea.pth.tar',
}

**Comment by 1adrianb** [comment]
Sorry for delay, I assume you already sorted this out, but for reference the models are saved/downloaded using https://pytorch.org/docs/stable/model_zoo.html#torch.utils.model_zoo.load_url and as such follow the default location indicated there.
