### ISSUE TITLE
Recommended resolution for head crops?

### ISSUE THREAD

**Issue by RSKothari** [1adrianb/face-alignment#176]
What resolution would you recommend I pass your module for head crops?

**Comment by 1adrianb** [comment]
The face alignment network takes as input a 256x256px image, out of which the face is around 200-220px height. 
That detector doesn't care too much about resolution as long as its not very small or extremely large (ie >1000px). Of course, smaller images will be faster at least during the face detection stage.

**Comment by RSKothari** [comment]
Thanks. In what range does the detector return the face crops? Is it normalized to the Surrey face model?

**Comment by 1adrianb** [comment]
No, there is no facial modeling involved. The detection themselves are following the Wider face dataset distribution while the crop adjustment its chosen empirically.
