### ISSUE TITLE
Pre-trained model of SFDDetector can be used for commercial application?

### ISSUE THREAD

**Issue by msuchoi** [1adrianb/face-alignment#179]
Thank you for your great work!

I have a question about the pre-trained model.
Pre-trained model of SFDDetector looks like trained on LS3D-W.
LS3D-W is also under the BSD license?

I wonder if the pre-trained model of SFDDetector is commercially available.

**Comment by 1adrianb** [comment]
Hi @msuchoi 
Thanks for your interest. I am unable to offer unfortunately an advice on this matter.
While we did generate the annotations and that particular parts are offered under BSD indeed, we don't own the images themselves, which include data from datasets such as 300W and it subsets (helen, lfpw etc), 300VW, AFLW etc. As such I am not sure how the licensing will work in this case. Sorry that I cannot be more helpful with this.
