### ISSUE TITLE
Differences in 2D and 3D landmarks are different for (x,y)

### ISSUE THREAD

**Issue by rakadambi** [1adrianb/face-alignment#190]
I am trying to understand 3D landmarks a bit more. And I am curious about one particular issue.

For a particular image, I see that the X and Y coordinates of landmarks and not exactly the same. I would have thought that the 3D landmarks coordinate would be same as those derived from 2D landmarks (x, y) plus the z coordinate. Essentially (x, y) would be the same.

Am I right in my assumption?

Thanks,

**Comment by Deccan12** [comment]
> I am trying to understand 3D landmarks a bit more. And I am curious about one particular issue.
> 
> For a particular image, I see that the X and Y coordinates of landmarks and not exactly the same. I would have thought that the 3D landmarks coordinate would be same as those derived from 2D landmarks (x, y) plus the z coordinate. Essentially (x, y) would be the same.
> 
> Am I right in my assumption?
> 
> Thanks,

Did you find the answer to this?

**Comment by LindgeW** [comment]
+1
