### ISSUE TITLE
No module named 'face_alignment.detection.blazeface'

### ISSUE THREAD

**Issue by nira100** [1adrianb/face-alignment#192]
Hello,

On line,
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device='cpu', face_detector='blazeface')
It is following the following error:
ModuleNotFoundError: No module named 'face_alignment.detection.blazeface'

Also, when testing on batches on s3fd, it shows the following error,
AttributeError: 'FaceAlignment' object has no attribute 'get_landmarks_from_batch'

Works fine on single images on s3fd.

**Comment by 1adrianb** [comment]
Hi @nira100  the blazeface was added recently by a contributor and its not yet in the pip or conda packages. I will push a new version later one this week. Can you install it from source in the meantime please?
