### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Machinegamer101** [1adrianb/face-alignment#194]
While trying to use it, i got the error while it was downloading 3DFAN4-7835d9f11d.pth.tar to the torch cache
I should also clarify that it downloads at 7-20kbps, and the error happens at around 60%

**Comment by 1adrianb** [comment]
I am really sorry that you are experiencing this. While I don't know your location, researchers from China previously reported similar issues.  Unfortunately there is not much that I can do without having a mirroring server there. Please see #62 for an workaround.

**Comment by Machinegamer101** [comment]
I ended up having to download them manually from the browser one by one at around 3:00 am here, so the download was around 300kbps, enough to finish it and then moved it to the torch cache. Thanks for your answer tho!
