### ISSUE TITLE
Is there a way to get the confidence of each point

### ISSUE THREAD

**Issue by galsk87** [1adrianb/face-alignment#195]
I would like to get the final confidence scores of each point to reduce the fp rate.
Is there a way to do so? 
If not is it possible to open a feature request?
Thanks!

**Comment by 1adrianb** [comment]
@galsk87 Currently this is not returned explicitly, however this information is available.
If you look at the value of the max of each heatmap here: https://github.com/1adrianb/face-alignment/blob/a6e1a6d1d7b2cc8a13e3fb32a53de75226a3c382/face_alignment/api.py#L164 you can retrieve the confidence of the network at that location.
