### ISSUE TITLE
Get error when loading  model

### ISSUE THREAD

**Issue by zhaoningning** [1adrianb/face-alignment#2]
hi @1adrianb ,  i get a error : "cPickle.UnpicklingError: invalid load key, '<'."   when i tried to load model, how this happen?

**Comment by 1adrianb** [comment]
@zhaoningning  Can you please offer more details regarding your setup? (which model you are trying to load etc). I have only tested in on a linux machine and with python 2.7 and 3.5/3.6 but.

**Comment by zhaoningning** [comment]
I tried 3DFAN-4.pth.tar and  2DFAN-4.pth.tar model, and get the same error;  
System is ubuntu14, I  use  python2.7, and  pytorch version is  0.2.0_3

**Comment by 1adrianb** [comment]
This is very weird, can you please check if the models are not corupted or load them in separe torch script? The travis builds for python 2.7 seems to be ok with the models and the tests are passing. I will anyway check in  Docker image if I can reproduce it.

**Comment by zhaoningning** [comment]
@1adrianb   Thanks for you advice!   I just checked the model, and found  the model  was not downloaded correctly(not completely)...

**Comment by 1adrianb** [comment]
@zhaoningning  Great! I am glad that it's fixed. I will update from urlib to urlib2 since the first one doesn't really tell to much if something fails.
