### ISSUE TITLE
rigid motion of the head

### ISSUE THREAD

**Issue by monabiyan** [1adrianb/face-alignment#20]
Hi Adrian

does your code can give rigid motion of the face? I mean 6 rigid values: 3 displacements, 3 rotational angles of the whole head?

**Comment by 1adrianb** [comment]
Hi @monabiyan, 
The code only provides the x,y,z coordinates of the points. However you should be able to compute them based on this.

**Comment by monabiyan** [comment]
Adrian, Thank you so much, Yes I do. Just wondering that.

Bests
