### ISSUE TITLE
Bounding box wasn't detect well

### ISSUE THREAD

**Issue by leovn85** [1adrianb/face-alignment#201]
Hi Adrian. First of all thank you for this amazing work !

Today, I used your project to detect face from some images, the face landmarks were detected well but there were some small cases that the bounding box didn't work well.

I've attached the screenshots from my work. And here is one example of image that the bounding box didn't work well: https://imgur.com/QHQMkBp

![2020-08-17 22_56_43-Window](https://user-images.githubusercontent.com/17286634/90417779-6a5c0b00-e0de-11ea-9044-0f0999d4d562.jpg)

**Comment by 1adrianb** [comment]
Hi, I am glad that you found it useful!

The SFD has some issues with high resolution images, if you can downsample it before passing it to the detector this will be both faster and likely more accurate. For example you could easily downsample that image 4x.
Alternatively, can you also try using the blaze face detector to test if this improves your results? (e.g.: fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device='cpu', face_detector='blazeface') )

**Comment by leovn85** [comment]
Thank you for your fast reply. I will try.
