### ISSUE TITLE
Input size of FAN network

### ISSUE THREAD

**Issue by marcobarnobi** [1adrianb/face-alignment#205]
I am trying to convert the pre-trained FAN network to ONNX for usage in C++. To do this I need to specify the input size of the network (channels, dim, dim). 
Could you help me to find this out in the code? 

@1adrianb

**Comment by 1adrianb** [comment]
3x256x256

**Comment by zhangyux15** [comment]
Hi! Have you convert the model to onnx? I successfully convert the onnx model, but I cannot parse with tensorrt...

> I am trying to convert the pre-trained FAN network to ONNX for usage in C++. To do this I need to specify the input size of the network (channels, dim, dim).
> Could you help me to find this out in the code?
> 
> @1adrianb

**Comment by 1adrianb** [comment]
@zhangyux15 Version 1.3.3 includes onnx models by default, I haven't tried them with Nvidia's tensorrt.

**Comment by debasishaimonk** [comment]
anyone able to convert to tensorRT?
