### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by hemanthyernagula** [1adrianb/face-alignment#208]
I installed face alignment package and after import this package I'm getting some error like this `OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.` Did anyone faced same issue?

**Comment by 1adrianb** [comment]
This doesn't seem to be an issue with the library itself. There are a few solution posted here https://github.com/dmlc/xgboost/issues/1715 than you can try.
