### ISSUE TITLE
What does the 0.12 factor means when calculating image center

### ISSUE THREAD

**Issue by dwy6626** [1adrianb/face-alignment#209]
As title, I am looking at your code and find the `centor` of an image is shifted by 0.12 times of the face width:

```python
# api.py
center = torch.FloatTensor(
  [d[2] - (d[2] - d[0]) / 2.0, d[3] - (d[3] - d[1]) / 2.0])
center[1] = center[1] - (d[3] - d[1]) * 0.12
```

Could someone tell me what does this means, thanks.

**Comment by 1adrianb** [comment]
Apologies for the delay. If its still relevant, that was simply used due to a shift present in the original data  vs the detected bounding box.
