### ISSUE TITLE
The miniconda path in Dockerfile is invalid.

### ISSUE THREAD

**Issue by DNATUNA** [1adrianb/face-alignment#213]
The current Dockerfile contains the installation path for miniconda as shown below.
```Dockerfile
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \     
     rm ~/miniconda.sh
```
![image](https://user-images.githubusercontent.com/28949165/96558679-ffee6380-12f6-11eb-8e37-18c6b7e56fe6.png)

However, an error occurs; you must change it as below to avoid an error.

```Dockerfile
RUN curl -o ~/miniconda.sh -O  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh
```

**Comment by JohanAR** [comment]
Maybe you could make a pull request to fix it?

**Comment by 1adrianb** [comment]
Thanks for reporting it and sorry for the delay.
