### ISSUE TITLE
How do the dots appear connected in the section "Detect 3D facial landmarks in pictures"

### ISSUE THREAD

**Issue by nira100** [1adrianb/face-alignment#214]
How do the dots appear connected in the images shown under the section "Detect 3D facial landmarks in pictures"?

**Comment by 1adrianb** [comment]
matplotlib, splitting the points in N group and then plotting them using the '-' style option.
You can find an example here: https://github.com/1adrianb/face-alignment/blob/master/examples/detect_landmarks_in_image.py
