### ISSUE TITLE
Only one axis has been checked in 3D landmark detection

### ISSUE THREAD

**Issue by vishal16babu** [1adrianb/face-alignment#225]
https://github.com/1adrianb/face-alignment/blob/250f4efea43ec7ef13ba7f5c15d80f9b85828bd1/face_alignment/api.py#L172
shouldn't it be `if pts[i, 0] > 0 and pts[i, 1] >0:` instead?

**Comment by 1adrianb** [comment]
Technically yes, this won't change for results of the network itself thought. Fixed.
