### ISSUE TITLE
SFD Training Code

### ISSUE THREAD

**Issue by tintinmovie** [1adrianb/face-alignment#231]
I would like to retrain the SFD model on my own dataset. Do you happen to have the training code for the model? I can't seem to find any other reports on GitHub with it.

Thanks 😄

**Comment by 1adrianb** [comment]
I am afraid I don't have the code any longer,  there are however quite a few repos available online for others SOTA face detections works that you can likely use. For most of the  cases you won't really notice any difference between them.
