### ISSUE TITLE
Warning: No faces were detected.

### ISSUE THREAD

**Issue by Deccan12** [1adrianb/face-alignment#232]
I am feeding correct face image but getting following error. For rest of the face images it is working fine but for few of them I am getting following error.

Warning: No faces were detected.
Traceback (most recent call last):

  File "<ipython-input-2-d983de3a759c>", line 7, in <module>
    preds = fa.get_landmarks(input_img)[-1]

TypeError: 'NoneType' object is not subscriptable

**Comment by 1adrianb** [comment]
@Deccan12 If you get the above warning, then, as the message states, the face detector was unable to detect one (perhaps too high or low resolution or the face is too much zoomed in). Of course you can experiment between the sf3d and the blazeface detector and see which one works better in your case. If you already know the location of the face, in terms of (x,y) coordinates of the bbox, then you can pass this information directly to the face alignment function.
