### ISSUE TITLE
Same output for 2d and 3d detectors?

### ISSUE THREAD

**Issue by Deccan12** [1adrianb/face-alignment#237]
I ran the code for 100's of images with following 2 detectors:

fa2D = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device='cpu', flip_input=True)

fa3D = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, device='cpu', flip_input=True)

But for both of these configuration, i got exact same output, of dimensions (68,3), is it normal or am I missing anything? Shouldn't 2D and 3D landmarks be different at least in dimensions?

**Comment by 1adrianb** [comment]
@Deccan12 I will assume you are overriding some of the variables somewhere.
For example, the following code works as expected (ie. the landmarks and their shape is different):
```
import face_alignment

fa2D = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device='cpu', flip_input=True)
fa3D = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, device='cpu', flip_input=True)

preds = fa2D.get_landmarks('face1.jpg')
print(preds)
preds = fa3D.get_landmarks('face1.jpg')
print(preds)
```

**Comment by Deccan12** [comment]
It does generate different ouput, does it have anything to do with flip_input argument?

**Comment by 1adrianb** [comment]
The ._2D should generate 68x2, and ._3D 68x3, with different locations in general. The ._2.5D should match with the 3D ones.
The flip argument simply runs the networks twice, once with normal image and another time with its flipped version. It then averages the predictions.
