### ISSUE TITLE
Do you have python code for model training? 

### ISSUE THREAD

**Issue by wjtan99** [1adrianb/face-alignment#24]
Do you have python code model training?  
Thanks a lot.

**Comment by 1adrianb** [comment]
@wjtan99 Not right now, but, I will integrate the python training code into this toward the end of this month. Sorry for this delay.

**Comment by wjtan99** [comment]
Thanks a lot. Looking forward to it.

**Comment by LeiyuanMa** [comment]
Looking forward to training code as well. Many thanks!
