### ISSUE TITLE
get_landmarks_from_directory 

### ISSUE THREAD

**Issue by oussamasf** [1adrianb/face-alignment#243]
when i call " `get_landmarks_from_directory`" i get this error 
get_landmarks_from_directory
```
/usr/local/lib/python3.6/dist-packages/face_alignment/detection/sfd/detect.py in batch_detect(net, img_batch, device)
     43     olist = [oelem.data.cpu().numpy() for oelem in olist]
     44 
---> 45     bboxlists = get_predictions(List(olist), batch_size)
     46     return bboxlists
     47 

TypeError: __init__() takes 1 positional argument but 2 were given
```

despite that i respected the doc instructions but still have same problem

**Comment by ekinim** [comment]
> when i call " `get_landmarks_from_directory`" i get this error
> get_landmarks_from_directory
> 
> ```
> /usr/local/lib/python3.6/dist-packages/face_alignment/detection/sfd/detect.py in batch_detect(net, img_batch, device)
>      43     olist = [oelem.data.cpu().numpy() for oelem in olist]
>      44 
> ---> 45     bboxlists = get_predictions(List(olist), batch_size)
>      46     return bboxlists
>      47 
> 
> TypeError: __init__() takes 1 positional argument but 2 were given
> ```
> 
> despite that i respected the doc instructions but still have same problem

I was trying on my computer, but I couldn't manage to import the face_alignment library. Then when I migrate to Google Colab, I faced the same issue.

**Comment by 1adrianb** [comment]
@ekinim what version of pytorch are you using? The minimum supported one is 1.5.x.

**Comment by 1adrianb** [comment]
@oussamasf could you try installing it from source please?

**Comment by oussamasf** [comment]
i m using pytorch 1.7.1

**Comment by 1adrianb** [comment]
@oussamasf thanks for the info, can you try installing the package directly from github source? It should be fixed now

**Comment by oussamasf** [comment]
the problem is fixed ,thank you so much !

**Comment by ekinim** [comment]
> @oussamasf thanks for the info, can you try installing the package directly from github source? It should be fixed now

Thank you Adrian, problem fixed. You are so kind and diligent.
