### ISSUE TITLE
Where can I find the complete network architecture?

### ISSUE THREAD

**Issue by dpnvnt** [1adrianb/face-alignment#249]
Hi, I was looking for the network architecture, is there any document explaining it in details?
I need it for a University project

Thank you in advance!

**Comment by 1adrianb** [comment]
See https://github.com/1adrianb/face-alignment/archive/v1.1.0.zip in face_alignment/models.py
Additionally you can visualize the current onnx models using https://github.com/lutzroeder/netron for example.
Finally, you can consult the paper: https://www.adrianbulat.com/downloads/FaceAlignment/FaceAlignment.pdf

**Comment by dpnvnt** [comment]
Thank you so much, another question... where can I find the onnx file referred to the network? I think that visualizing it with netron would be very useful for us

**Comment by 1adrianb** [comment]
You can use the zip I pointed you out too, then use the [pytorch onnx module](https://pytorch.org/docs/stable/onnx.html) to export it and visualize it in netron.

**Comment by FPerezHernandez92** [comment]
Hi. Currently I need to obtain the landmarks of lateral faces. I have tried the face_alignment tool and it works very well, congratulations. I wanted to ask how to export the model to ONNX as I have not found the solution. The model I want to export is 2DFAN4-cd938726ad.zip. Thank you very much for your help
