### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by moncio** [1adrianb/face-alignment#250]
Hi, I'm discovering a problem sometimes at the first detection of the library. It seems the system in this first detection, it needs a large quantity of GPU memory coming the next error:

**_RuntimeError: CUDA out of memory. Tried to allocate 2.26 GiB (GPU 0; 10.76 GiB total capacity; 355.45 MiB already allocated; 2.27 GiB free; 2.38 GiB reserved in total by PyTorch_**

My computer is equipped by RTX 2080 ti with 11 GB (I'm executing other algorithms at the same time). My question is why the library is consuming so many GB at the beginning (Watching nvidia-smi command), I observe almost 8 GB but quickly decrease to 4 GB keeping this rate all the execution)

Thanks in advance

**Comment by 1adrianb** [comment]
Hi @moncio 
The detector memory usage, in particular of SFD will depend on the resolution of input image. You can control/limit this by resizing your image prior to this. Note that some faces may be missed if they get to small. Alternatively, you can try the blaze face detector which should use less.

**Comment by moncio** [comment]
In this case, I'm using the BlazeFace and I tried to downsample and the issue continues...

**Comment by 1adrianb** [comment]
If you already did that, in this case most likely its the cudnn benchmarking flag that during the first run will try different algorithms, see for example [[1]](https://discuss.pytorch.org/t/larger-gpu-memory-usage-during-the-first-batch/58768).
As such, you could warm-up the network prior to running the rest of your code. Disabling the benchmarking may lead to slower execution.
