### ISSUE TITLE
License of pre-trained model

### ISSUE THREAD

**Issue by danperazzo** [1adrianb/face-alignment#260]
Hello everyone, thanks for licensing this excellent work! Just a question, what is the license of the pre-trained model? Can we use it for a commercial solution?

**Comment by 1adrianb** [comment]
Please note that this is not a legal advice. 
The code and the models are offered under BSD-3 Clause, however we don't own the images used for training (300W, 300W-LP, AFLW etc). As such its best to check what is the implication of this with the authors of the datasets.

**Comment by danperazzo** [comment]
Ok, thank you!
