### ISSUE TITLE
Problem because of getaddrinfo

### ISSUE THREAD

**Issue by meherabhi** [1adrianb/face-alignment#261]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /home/mtech/kmeher/.cache/torch/hub/checkpoints/s3fd-619a316812.pth

for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

How to solve this issue?

**Comment by 1adrianb** [comment]
It looks that there are some network access issues, thought the endpoint is up. You can bypass this by manually downloading this file and place it in the expected location (i.e. /home/mtech/kmeher/.cache/torch/hub/checkpoints/s3fd-619a316812.pth).
