### ISSUE TITLE
Warning: No faces were detected.

### ISSUE THREAD

**Issue by JOST777** [1adrianb/face-alignment#265]
I'm wondering if it would make sense to make this an actual warning instead of a `print` call. My work flow involves processing many images where only a fraction contain faces, so its inconvenient to print a line every time that happens. Maybe there is a recommended pre-screening procedure? But even then, I think I would still want to suppress the message in the event that it did happen.

**Comment by 1adrianb** [comment]
Agree, this makes sense to me. Feel free to make a pull request if you prefer. If not I can adjust it this week.
