### ISSUE TITLE
Output of `preds`

### ISSUE THREAD

**Issue by SchJas** [1adrianb/face-alignment#268]
The code provided here for 3D landmarks.

`import face_alignment
from skimage import io

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False)

input = io.imread('../test/assets/aflw-test.jpg')
preds = fa.get_landmarks(input)`

I wanted to ask before I install the package. So just to clarify, if I were to print `preds` I should obtain a (68,2) array, which contains the 68 facial landmark points on the face?

**Comment by 1adrianb** [comment]
For the 3D flag passed in the example the array will be (68,3). If you pass _2D or _2halfD they will be indeed (68,2). If multiple faces are present a list of arrays will be returned.

**Comment by tianqi-zhao** [comment]
And what the three values means for 3D? For 2D, it is the coordinate of image like (x, y), but I can't understand the meaning for 3D. There are even negative numbers.
