### ISSUE TITLE
Boost.Python.ArgumentError: Python argument types in

### ISSUE THREAD

**Issue by HaiCheng16** [1adrianb/face-alignment#27]
Python 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_alignment
>>> from skimage import io
>>>
>>> fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=True, flip_input=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/face_alignment/api.py", line 84, in __init__
Boost.Python.ArgumentError: Python argument types in
    cnn_face_detection_model_v1.__init__(cnn_face_detection_model_v1, str)
did not match C++ signature:
    __init__(_object*, std::string)
>>>

**## **I installed pytorch ,cudatoolkit and cudnn via conda,but if I set enable cuda=True, the mistake occurs and if I set enable cuda=False, it works fine.  Is anyone can help?****

**Comment by 1adrianb** [comment]
Hi @HaiCheng16 , this looks like a problem with the installation of dlib.
Check this: https://github.com/davisking/dlib/issues/199 maybe it helps, but basically try to reinstall dlib making sure it is combiled against the correct boost and python libs.

**Comment by HaiCheng16** [comment]
thanks for your reply,my dlib version is 19.5.0. Then I reinstalled it by the version 19.7.0,but the problem still exists. I also compiled my boost libray via python provided by conda . But,it still not working .

**Comment by HaiCheng16** [comment]
I run a docker instead ,and it works,thank you anyway.
