### ISSUE TITLE
Could you update the output of the function.

### ISSUE THREAD

**Issue by sunshower76** [1adrianb/face-alignment#270]
Hi!
I really appreciate your work!
but, It will be good If we can get a detection bounding box also.

Could you add the additional option to get the bounding box of the landmark?

Thanks!

**Comment by 1adrianb** [comment]
Hi, sure I can add a flag for this and return the detected bounding boxes too.
The same can be achieved by calling the face detector https://github.com/1adrianb/face-alignment/blob/2bcfcc6ea20d0104d48942737639827fd3d5e816/face_alignment/api.py#L126 before the face alignment and then passing the bounding boxes to it. But I agree sometimes its more convenient to return the bboxes in one go too.
