### ISSUE TITLE
Addition of confidence scores & bounding boxes doesn't handle "No faces were detected." gracefully.

### ISSUE THREAD

**Issue by MarkuzK** [1adrianb/face-alignment#272]
Hey, I appreciate the addition of the confidence scores being returnable with the landmark values. But it seems that the handling of images that have no faces / no faces being detected is not done properly yet.

[...]/face-alignment/face_alignment/api.py:144: UserWarning: No faces were detected.
  warnings.warn("No faces were detected.")
Traceback (most recent call last):
[...]
File "[...]/face-alignment/face_alignment/api.py", line 243, in get_landmarks_from_batch
    landmark_set, landmarks_scores, _ = res
TypeError: cannot unpack non-iterable NoneType object

In the case that confidence scores are enabled, get_landmarks_from_image still only returns a single None value when 3 values are expected.

Cheers,

      Markus

**Comment by 1adrianb** [comment]
Sorry for this, it should be fixed now.
