### ISSUE TITLE
ValueError when adding `device='gpu'`

### ISSUE THREAD

**Issue by Sentero-esp12** [1adrianb/face-alignment#276]
I'm getting this error:
```
Exception has occurred: ValueError
exception: no description
```
at this line:
```
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False, device='gpu')
```
when I set `device='gpu'`

It runs fine when I set it to `cpu`.

GPU: 750 ti
Driver Version: 465.19.01
CUDA Version: 11.3

**Comment by 1adrianb** [comment]
@Sentero-esp12 The values supported match the ones supported by pytorch. For cpu, `device='cpu'` while for gpu `device='cuda'`. A specific gpu can be specified like this: `device='cuda:0'`
