### ISSUE TITLE
Issue with the python code 

### ISSUE THREAD

**Issue by LinusLGL** [1adrianb/face-alignment#282]
Hi,

I got the TypeError: __init__() got an unexpected keyword argument 'face_detector_kwargs'

how do i resolve this problem

![image](https://user-images.githubusercontent.com/46456480/128206097-2bf2c166-d4f5-4c0e-9ef8-26d8564cf6f1.png)

**Comment by 1adrianb** [comment]
Marked as duplicate of #281 

Please use the same issue that you opened previously to discuss this.
