### ISSUE TITLE
RuntimeError: getrf : Lapack library not found in compile time

### ISSUE THREAD

**Issue by qmj123** [1adrianb/face-alignment#29]
Hello! when I run 'python detect_landmarks_in_image.py', it can't work.
the erro is : RuntimeError: getrf : Lapack library not found in compile time
 at /home/qwe/pytorch/aten/src/TH/generic/THLapack.c:140
Could you help me? 
Thanks a lot.

**Comment by 1adrianb** [comment]
Hi @qmj123, you need to install/compile  OpenBlas (or any other blas libray for that matter).

**Comment by qmj123** [comment]
I am very excited to see your reply.
ok! I try.
Thank you very very  much!
