### ISSUE TITLE
 get_landmarks_from_image() got an unexpected keyword argument 'return_landmark_score'

### ISSUE THREAD

**Issue by segalinc** [1adrianb/face-alignment#290]
Hi there, 
I have the latest version of face-alignment (1.3.4) but I get the error that return_landmark_score in't available
Any hint?

Thank you

**Comment by usamaamjad7** [comment]
if you use colab notebook please input   !pip install face_alignment -q  --upgrade

**Comment by segalinc** [comment]
I am not using colab
