### ISSUE TITLE
Error: can't convert cuda:0 device type tensor to numpy.

### ISSUE THREAD

**Issue by GaryGky** [1adrianb/face-alignment#292]
![image](https://user-images.githubusercontent.com/47270685/133417258-d35909f6-4abb-42bc-b74a-c2f7f80a0379.png)

When I try to predict landmarks with method: get_landmarks(), in line 126, we have a numpy array, but in line 138, we have a tensor default to locate in cuda:0 if GPU is available. But in line 142, we try to calculate a tensor on cuda and numpy array. So I got the problem:
"can't convert cuda:0 device type tensor to numpy."

I wonder if this is a bug or I use the api in a wrong way.

**Comment by MZHI** [comment]
Hi! I think it is not a bug, because the description for method 'crop' from https://github.com/1adrianb/face-alignment/blob/master/face_alignment/utils.py says that image and center must be of type np.array. So, just create center of type np.array instead of torch.tensor
