### ISSUE TITLE
Elements in Bounding Boxes

### ISSUE THREAD

**Issue by gitjohnnygit** [1adrianb/face-alignment#298]
Hello @1adrianb, many thanks for your powerful work!

I can't figure it out why bounding_boxes contains 5 elements when a face is detected? The first four values are (x, y, x+w, y+h) with no doubt. But what is exactly the fifth value which is lower than 1 for the test image aflw-test?

Would appreciate for any comments.

**Comment by 1adrianb** [comment]
Hi @gitjohnnygit 

The last value is the confidence of the detected bounding box.

**Comment by gitjohnnygit** [comment]
Hi @1adrianb 

I see! Many thanks for your quick reply.
