### ISSUE TITLE
Slow inference speed in first 2 images

### ISSUE THREAD

**Issue by Mofafa** [1adrianb/face-alignment#304]
Hi, thanks for your wonderful work!

I tried to get face landmarks for a group of images in a for loop, and I found that it is always slow in the first 2 images.

<img width="266" alt="time" src="https://user-images.githubusercontent.com/28086790/150130071-d8f90cca-e3a2-47d8-a207-4b38981d0e7e.png">

I used 3D model and "get_landmarks_from_image" function.

Why?

**Comment by 1adrianb** [comment]
Hi, during the first iteration some internal buffers are initialized and the model is basically warmed up + the torch.backends.cudnn.benchmark makes a few checks to find the optimal algorithms for the convs.

**Comment by Mofafa** [comment]
> Hi, during the first iteration some internal buffers are initialized and the model is basically warmed up + the torch.backends.cudnn.benchmark makes a few checks to find the optimal algorithms for the convs on the given hardware.

Thank you!
