### ISSUE TITLE
Terminology Issues for Face Alignment and Keypoint Detection

### ISSUE THREAD

**Issue by xieyipeng** [1adrianb/face-alignment#309]
* This `face-alignment` is for face key point detection,But how should I do the real alignment operation?

* Like an affine transformation, keeping the eyes on the horizon?

* I want to know the most formal, real alignment

* thak u!

**Comment by 1adrianb** [comment]
The terminologies are largely used interchangeable. 
This reflects how historically face alignment/key points detection was performed: one would take a deformable facial model and align it with an image such that the model will now match the location of a set of desired fiducial points. 

A good reference for this is the work from Gu&Kanade (https://link.springer.com/referenceworkentry/10.1007/978-0-387-73003-5_186)
