### ISSUE TITLE
coordinate system of 3D landmarks?

### ISSUE THREAD

**Issue by crisie** [1adrianb/face-alignment#31]
Hi,

I'm interested in getting the 3D landmarks position with respect to the camera, having a pretty accurate intrinsic camera parameters estimate. I thought I could do that by applying solvePnP to the 2D and 3D landmarks to obtain the face position and rotation if the reference frame of the 3D landmarks is the center of the face/head, but after some tests this is not really clear to me. 

Could you please tell me the coordinate system of the 3D landmarks, in order to compute the 3D location of these landmarks wrt to camera? Or is there any straightforward way to compute the 3D camera landmarks already with your method?

Thanks!

**Comment by 1adrianb** [comment]
Hi @crisie 
First, I am really sorry for the delay. The models were trained on [300W-LP](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm) dataset which uses a Basel 3DMM model. As a result the coordinates are predicted with respect to the head center. All the predictions should be in concordance with he 3DMM model mentioned above. 
Unfortunatelly the code doesn't provide a direct method to estimates the landmarks w.r.t. to the camera.

Please let me know if i can by of assistance.

**Comment by Tony1Q84** [comment]
@crisie Hi, I am also interested in calculating the position and rotation of the 3D landmarks, so have you solved the problem, could you tell me?

**Comment by zjs820** [comment]
same question here, would be helpful if someone knows, thanks!

**Comment by CXiaoDing** [comment]
I have the same question and have not found any good solution. Can anyone help?

**Comment by Selimonder** [comment]
+1 to this.

**Comment by hengfei-wang** [comment]
Same here?
