### ISSUE TITLE
Subpixel regression

### ISSUE THREAD

**Issue by Illeke** [1adrianb/face-alignment#310]
Dear @1adrianb,
I was wondering if this repo includes the code mentioned in your paper "Subpixel Heatmap Regression for Facial Landmark Localization"? I wasn't able to see any mention of it in the release notes. I am working on my master's dissertation and would love to run the code for some comparisons. Thank you in advance and have a nice day!

**Comment by Illeke** [comment]
Implemented it successfully myself.

**Comment by Amanit** [comment]
Dear @Illeke, could you share the code please?
