### ISSUE TITLE
Can not change device to 'cuda:1' for faceAlignment 

### ISSUE THREAD

**Issue by ZhenyanSun** [1adrianb/face-alignment#314]
for I have cuda 0,1,2,3 but it specifies to 0 always.

**Comment by 1adrianb** [comment]
You should be able to change this by passing the device explicitly: e.g.: ```device = 'cuda:1'``` when constructing the model.
Alternatively, if you are running this as a separate script you can export the CUDA_VISIBLE_DEVICES=3 (for the 4th gpu) before calling you script.

**Comment by ZhenyanSun** [comment]
> You should be able to change this by passing the device explicitly: e.g.: `device = 'cuda:1'` when constructing the model. Alternatively, if you are running this as a separate script you can export the CUDA_VISIBLE_DEVICES=3 (for the 4th gpu) before calling you script.

Thanks very much for your reply. Before I specify the os.environ["CUDA_VISIBLE_DEVICES"]="3" and also specify the device = 'cuda:3', then there was cuda error.
