### ISSUE TITLE
If I downloaded pre-trained model manually, how can I use it with `face_alignment.FaceAlignment`  ?

### ISSUE THREAD

**Issue by anewusername77** [1adrianb/face-alignment#320]
Hey there,
The code I use is:
```python
landmarksDetector = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False, device=self.device)
```
and the output in terminal is: 
```
Downloading: "https://www.adrianbulat.com/downloads/python-fan/3DFAN4-7835d9f11d.pth.tar" to ...
```
Because of the downloading problem, I manually downloaded the pre-trained model , now I just want to use it with api. 
Big thanks if you can help me!

**Comment by sairampillai** [comment]
@anewusername77 Did you find a workaround?

**Comment by sxs4337** [comment]
Same question.
Want to remove the dependency of the API to download model.
