### ISSUE TITLE
Where is Face Alignment?

### ISSUE THREAD

**Issue by DungLeMTA** [1adrianb/face-alignment#324]
As my opinion, this repository is the Landmarks of Face, it is not Face Alignment? Where I can find it?

**Comment by imxtx** [comment]
You are right. It is just a landmarks detection tool. The name is missleading.

**Comment by 1adrianb** [comment]
Face alignment and key points localisation are used interchangeable in the literature. The former reflects the historical way of detecting the facial fiducial points on a face by aligning a shape model to a face. See for definition: https://link.springer.com/referenceworkentry/10.1007/978-0-387-73003-5_186

Given the points, one can compute a transformation to align the textures of two face too, using for example a shape model. There are a few implementation around, some that points detected with this repo. Note however that this goes beyound the scope of this repo, which is to offer an implementation for our paper.
