### ISSUE TITLE
Problem installing dependencies

### ISSUE THREAD

**Issue by anaspapa24** [1adrianb/face-alignment#33]
Hello , I have a problem when i try to install the dependences for the face alignment lib. The problem appears to be on the dlib, but i don't know how to fix it. Here are my logs
`Running setup.py bdist_wheel for dlib ... error
  Complete output from command /home/tasos/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KtTWRq/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpSfH_cypip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  Detected Python architecture: 64bit
  Detected platform: linux2
  Configuring cmake ...
  /home/tasos/anaconda2/bin/cmake: /home/tasos/anaconda2/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/tasos/anaconda2/bin/cmake)
  error: cmake configuration failed!
  
  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command /home/tasos/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KtTWRq/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-p5mzmg-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Detected Python architecture: 64bit
    Detected platform: linux2
    Removing build directory /tmp/pip-build-KtTWRq/dlib/./tools/python/build
    Configuring cmake ...
    /home/tasos/anaconda2/bin/cmake: /home/tasos/anaconda2/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/tasos/anaconda2/bin/cmake)
    /home/tasos/anaconda2/bin/cmake: /home/tasos/anaconda2/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/tasos/anaconda2/bin/cmake)
    error: cmake configuration failed!
    
    ----------------------------------------
Command "/home/tasos/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KtTWRq/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-p5mzmg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-KtTWRq/dlib/
`

Could you suggest a solution?
Thank you.

**Comment by 1adrianb** [comment]
Hi @anaspapa24 
Please try to install the missing library. On ubuntu you can simple run:
``sudo apt-get install libstdc++6``
for more, please check this: https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

**Comment by Mastergalen** [comment]
If you're using Anaconda the fix is to manually relink libraries:

https://github.com/ContinuumIO/anaconda-issues/issues/5191#issuecomment-368243432
