### ISSUE TITLE
test_error!!!!!!

### ISSUE THREAD

**Issue by AresGao** [1adrianb/face-alignment#34]
when I run examples,it needs download model; I quit it,and then i run it again, the error comes up!!!!!!!!!!!!!!!!!!!So what can I do????
-----------------------------------------------------------------------------------------------------------------------------------
ERROR: test_predict_points (__main__.Tester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/facealignment_test.py", line 7, in test_predict_points
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=False)
  File "build/bdist.linux-x86_64/egg/face_alignment/api.py", line 131, in __init__
    map_location=lambda storage,
  File "/home/gaozhihua/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/home/gaozhihua/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 418, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: unexpected EOF. The file might be corrupted.

----------------------------------------------------------------------
Ran 1 test in 4.614s

FAILED (errors=1)

**Comment by 1adrianb** [comment]
@AresGao A hidden folder was added to your home folder (it should be something named .facealignment ). Please emove it and rerun the installation.

**Comment by AresGao** [comment]
@1adrianb Eh.......Then I got this......what can i do??
----------------------------------------------------------------------------------------------------------------
Downloading the face detection CNN. Please wait...
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, enable_cuda=True, flip_input=False)
  File "build/bdist.linux-x86_64/egg/face_alignment/api.py", line 85, in __init__
Boost.Python.ArgumentError: Python argument types in
    cnn_face_detection_model_v1.__init__(cnn_face_detection_model_v1, str)
did not match C++ signature:
    __init__(_object*, std::string)

**Comment by AresGao** [comment]
@1adrianb The python dlib detect loader can not work corroct, what is your python version?I use 2.7,conda.

**Comment by 1adrianb** [comment]
@AresGao  this is most likely a problem between the libboost  version from your system and the one used to build dlib. I think there was a similar issue opened on the dlib github page. As an alternative you can run dlib in CPU mode which should work.

**Comment by fauziwei** [comment]
@1adrianb 

I have same issue on windows 10.

Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_alignment
>>> face_alignment.__version__
'0.1.0'
>>> from face_alignment import FaceAlignment, LandmarksType
>>> FACE_ALIGNMENT = FaceAlignment( LandmarksType._2D, enable_cuda=True, flip_input=False )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\face2face\faceswap\faceswap_other\df\face-alignment\face_alignment\api.py", line 106, in __init__
    map_location=lambda storage,
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\serialization.py", line 476, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: unexpected EOF. The file might be corrupted.
>>>

reinstall torch and face_alignment, still cannot solve it.

**Comment by fauziwei** [comment]
clean C:\Users\xxx\AppData\Local\face_alignment\data\
solved.

**Comment by YakshThakar** [comment]
[Solved]Clean cache of your pc
after that also clean path="C:\Users\Admin\AppData\Local\face_alignment"
run script face_alignment.py  then wait for downloading Face Alignment Network(FAN)!!
After that it works Fine!! @AresGao
