### ISSUE TITLE
Why I just can't run the test case you provided?

### ISSUE THREAD

**Issue by AWGiaGia** [1adrianb/face-alignment#354]
I use the command you provided to install the face-alignment. And then I run the case code as below:
```
import face_alignment
from skimage import io

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False)

preds = fa.get_landmarks_from_directory('../test/assets/')
```
I change the director folder to my own dataset, and run this code, where it reported an error:
```
AttributeError: partially initialized module 'face_alignment' has no attribute 'FaceAlignment' (most likely due to a circular import). Did you mean: 'face_alignment'?
```
 
Then how should I do?

**Comment by Imane219** [comment]
> I use the command you provided to install the face-alignment. And then I run the case code as below:
> 
> ```
> import face_alignment
> from skimage import io
> 
> fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False)
> 
> preds = fa.get_landmarks_from_directory('../test/assets/')
> ```
> 
> I change the director folder to my own dataset, and run this code, where it reported an error:
> 
> ```
> AttributeError: partially initialized module 'face_alignment' has no attribute 'FaceAlignment' (most likely due to a circular import). Did you mean: 'face_alignment'?
> ```
> 
> Then how should I do?

hi, i have the same question. Can you tell me how you solve this problem? Thank you!

**Comment by AWGiaGia** [comment]
Oh, I am bummed! I should not have named the file “face_alignment”, which conflicts with the library's name
