### ISSUE TITLE
Exception can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by subtlevenom** [1adrianb/face-alignment#362]
Repro steps (just following the steps from https://pypi.org/project/face-alignment/1.4.1/):

fal = fa.FaceAlignment(landmarks_type= fa.LandmarksType.TWO_D, face_detector='sfd', dtype=torch.bfloat16, device='cuda')
preds = fal.get_landmarks(img)

img is a numpy array [H,W,3]

Exception:
TypeError("can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.")

**Comment by subtlevenom** [comment]
It seems it is a duplicate of https://github.com/1adrianb/face-alignment/issues/292, which is still open. Looks like a showstopper issue

**Comment by 1adrianb** [comment]
@subtlevenom I've pushed a quick fix, if you reinstall it from source it should now be fine
