### ISSUE TITLE
Can not access to https://www.adrianbulat.com/downloads/python-fan/3DFAN-4.pth.tar

### ISSUE THREAD

**Issue by ghtwht** [1adrianb/face-alignment#37]
Hi, Adrian,
     Thanks for sharing your code.
     I came across the error "urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)" when ran the facealignment_test.py in the test folder, and found that I cannot access to the alignment network(FAN) url.

**Comment by 1adrianb** [comment]
Hi @ghtwht ,
I check the websites certificate and it seems to be fain. Can you please try one the solutions available on stackoverflow ? (ex: https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c/41692664 )
If the problem still persists please try to download it manually and then copy it to the hidden faca_alignment folder found in your home folder.

**Comment by ghtwht** [comment]
Hi, Adrian,
Thanks for replying me, I have solved the problem with your suggestions. Your enthusiasm and politeness impressed me, and I really really like you.  ^_^
