### ISSUE TITLE
the speed of get_landmarks() for one image

### ISSUE THREAD

**Issue by zhouhui1992** [1adrianb/face-alignment#40]
the code is as below:
`fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, enable_cuda=True, flip_input=False)
input = cv2.imread('036.jpg')
s0 = time.time()
preds = fa.get_landmarks(input[:,:,(2,1,0)])
s1 = time.time()
print s1-s0`

the picture resolusion is 112x96, it takes about 1.75s for one image processing, is it right?
i feel the speed is a little bit slow.

**Comment by 1adrianb** [comment]
Hi @zhouhui1992 
For a better timing you should run it multiple times. The first forward pass is ussualy slower due to all initialisations that happen in behind.
Now, while it depends on the hardware used, the landmarks localisation network alone can achieve 20fps on a 1080 Ti GPU. This timing doesn't include the face detector time and unfortunatelly dlib is very slow.

To summarize: the slowdown is caused by dlib face detector (most likely), but for better timing run the get_landmarks multiple times.

**Comment by zhouhui1992** [comment]
thank you for your reply . I rerun the test multiple times and the time is as fast as you said. I found another problem that the landmark of some picture can not be get  due to the dlib face detector model, so can i use my own face detector to replace the dlib detector? is it will have a bad effect on the face landmark precision when change the face detector?

**Comment by 1adrianb** [comment]
@zhouhui1992 The models were not trained using dlib so you can safely replace it with other face detectors, as long as it doesnt work worse than dlib :) 
Also, at the moment the python model uploaded performs worse than the lua counterpart, so if you need more accuracy for now you can have a look at: https://github.com/1adrianb/2D-and-3D-face-alignment

**Comment by 1adrianb** [comment]
@zhouhui1992  Also if you have an opensource face detection model that you would like to share, feel free to make a pull request :)

**Comment by zhouhui1992** [comment]
sorry about for later reply. i'm thinking about use mtcnn to replace the dlib because that mtcnn has higher recall. I test your new upload model and found the landmarks of one picture in the webface are error.,while he older model gives the right landmarks.

![001](https://user-images.githubusercontent.com/21094655/35087307-bc83345e-fc6a-11e7-9a56-ea60f48e3f15.jpg)
![landmark](https://user-images.githubusercontent.com/21094655/35087485-4bab6016-fc6b-11e7-9aa7-96abf1176177.jpg)
