### ISSUE TITLE
KeyError: 'state_dict'

### ISSUE THREAD

**Issue by liuhengli** [1adrianb/face-alignment#44]
I run the test code in this 'fan_dict = {k.replace('module.', ''): v for k, v in fan_weights['state_dict'].items()}' line have a error KeyError: 'state_dict'

**Comment by 1adrianb** [comment]
Hi @liuhengli  can you please make sure that you are using the latest version? Can you please do a git pull or reclone it?

**Comment by liuhengli** [comment]
ok, thanks

**Comment by 1adrianb** [comment]
@liuhengli, did it worked?

**Comment by liuhengli** [comment]
Yes, I have solved. Thanks
I found the keypoints have some jitter when using usb camera for testing. if I want to solved this problem could you give me some advice

**Comment by 1adrianb** [comment]
@liuhengli check as an example this: https://www.kaggle.com/selfishgene/animating-and-smoothing-3d-facial-keypoints/ (they are actually using this method I think)
another approach is to run it twice on the same image, initialising the second time from the previous bunding box (defined by the detected points).

**Comment by liuhengli** [comment]
@1adrianb OK, Thank you very much. I will try it, thanks.
