### ISSUE TITLE
No module named face_alignment

### ISSUE THREAD

**Issue by sbyNiceBlowJob** [1adrianb/face-alignment#46]
I 've already followed your setup instructions, but still got this issue.

**Comment by 1adrianb** [comment]
@sbyNiceBlowJob have you encoutered any errors while running ``python setup.py install``? Because it looks like the module is not installed.

**Comment by sbyNiceBlowJob** [comment]
No, it says **Finished processing dependencies for face-alignment==0.1.0**

**Comment by sbyNiceBlowJob** [comment]
It's all right. I delete the minicode2 filefolder, and it works well now.

**Comment by sbyNiceBlowJob** [comment]
You 've really done a great job. I 'd like to ask a few more questions. Are all the images in your dataset annotated with exactly 68 points? And do you know any face alignment dataset which has annotated points more than 68 points?
