### ISSUE TITLE
try this image,not workable.

### ISSUE THREAD

**Issue by leaf918** [1adrianb/face-alignment#47]
![2s](https://user-images.githubusercontent.com/170311/35715201-ff69aabc-080b-11e8-89a3-4b355e6a6ad5.jpg)

**Comment by 1adrianb** [comment]
Can you please define what do you mean by this?

**Comment by leaf918** [comment]
cannot detect face landmark

**Comment by 1adrianb** [comment]
@leaf918 the face detecor used (dlib) probably cannot detect it. Please replace it with other face detection method (suitable for large poses)

**Comment by xxllp** [comment]
@1adrianb ，could you get an example
