### ISSUE TITLE
Failed to download network file when run example

### ISSUE THREAD

**Issue by room3dev** [1adrianb/face-alignment#48]
Hi, I'm trying to run example code (detect_landmarks_in_image.py) but it failed to download network file, so I try again but this time It doesn't restart the download and show[ 'RuntimeError: unexpected EOF. The file might be corrupted'](https://imgur.com/a/KiMku) instead. How can I fix this? 

`(d) E:\DeepLearning\Repositories\face-alignment\examples>python detect_landmarks
_in_image.py
Downloading the Face Alignment Network(FAN). Please wait...
Downloading the Face Alignment depth Network (FAN-D). Please wait...
Traceback (most recent call last):
  File "detect_landmarks_in_image.py", line 8, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_c
uda=False, flip_input=False)
  File "E:\Anaconda3\envs\d\lib\site-packages\face_alignment-0.1.0-py3.6.egg\fac
e_alignment\api.py", line 125, in __init__
  File "E:\Anaconda3\envs\d\lib\urllib\request.py", line 289, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only
 9977475 out of 234708217 bytes>

(d) E:\DeepLearning\Repositories\face-alignment\examples>python detect_landmarks
_in_image.py
Traceback (most recent call last):
  File "detect_landmarks_in_image.py", line 8, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_c
uda=False, flip_input=False)
  File "E:\Anaconda3\envs\d\lib\site-packages\face_alignment-0.1.0-py3.6.egg\fac
e_alignment\api.py", line 129, in __init__
  File "E:\Anaconda3\envs\d\lib\site-packages\torch\serialization.py", line 261,
 in load
    return _load(f, map_location, pickle_module)
  File "E:\Anaconda3\envs\d\lib\site-packages\torch\serialization.py", line 416,
 in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: unexpected EOF. The file might be corrupted.
`

I'm using Anaconda, env python 3.6
Windows 7, pytorch_legacy  0.3.0 (by peterjc123)
I can "import face_alignment" without error.

**Comment by 1adrianb** [comment]
Hi @room3dev probably the connection droped for some reasons during the downloading. Please remove the corrputed model and the code will try to redownload it.

**Comment by xxllp** [comment]
不知道model 下载的路径，郁闷

**Comment by PalmLand** [comment]
> 不知道model 下载的路径，郁闷

it downloads in C:\Users\YOUR_USER_NAME\AppData\Local\face_alignment\data, if your PC's system is windows.
