### ISSUE TITLE
find some problems while running python setup.py install

### ISSUE THREAD

**Issue by PyJulie** [1adrianb/face-alignment#49]
> Processing dependencies for face-alignment==0.1.0
> Searching for opencv-python
> Reading https://pypi.python.org/simple/opencv-python/
> No local packages or working download links found for opencv-python
> error: Could not find suitable distribution for Requirement.parse('opencv-python')

how can i reslove it, and when need i to run python setup.py build? before install or after?

**Comment by 1adrianb** [comment]
Hi @PyJulie  sorry for this, please try ``pip install opencv-python``
