### ISSUE TITLE
Detected face landmarks are rounded to integer 

### ISSUE THREAD

**Issue by LexSong** [1adrianb/face-alignment#5]
Is it the correct behavior?

**Comment by LexSong** [comment]
I just traced the code, looks like the landmarks are maximum of 64x64 heatmap.
So the detected landmarks should be on the heatmap grid.

**Comment by 1adrianb** [comment]
@LexSong Yes, you are right. You can probably keep them real but this will not matter to much in practice.

**Comment by LexSong** [comment]
@1adrianb I just tried the landmark detector on a video, and the "rounding" landmarks are jumping around between video frames. The movement is not smooth. I will add a smooth filter to solve my issue. Thanks for your help

**Comment by 1adrianb** [comment]
@LexSong Yes, smoothing should defenitly help. Is the "jump" significant? In the video that I generated the next frame was initialised with the previous prediction (the bbox of the prediction) which made the results more stable than using a detector. I don't know however if it we be useful also in your case.
Also, if time is not an issue you can run it twice on the same frame (first using the detected bbox and then by running it using the newly obtained bbox).

**Comment by LexSong** [comment]
@1adrianb Thanks, I'll do more experiments
