### ISSUE TITLE
KeyError: 'unexpected key "state_dict" in state_dict'

### ISSUE THREAD

**Issue by ZeroCool22** [1adrianb/face-alignment#50]
Tried to find a solution but i couldn't get one...

![screenshot_12](https://user-images.githubusercontent.com/13344308/36062126-b56a9c66-0e44-11e8-95ec-a2f36c1fa804.png)

![screenshot_5](https://user-images.githubusercontent.com/13344308/36062316-ed972b0a-0e48-11e8-96f2-46f55638bc1a.png)

Need to change something there or...?

**PD:** I have the latest version of the REPO.

**Comment by 1adrianb** [comment]
Hi @ZeroCool22, thanks a lot for the detailed description. Could you please try to remove the downloaded model (you can do this manually ot by running ``remove_models()``).

**Comment by ZeroCool22** [comment]
Thx for the reply @1adrianb, sorry for the dumb question but you mean this models?

![models](https://user-images.githubusercontent.com/13344308/36063341-774931c0-0e5a-11e8-9688-8594c385f1ba.png)

**Comment by ZeroCool22** [comment]
OK, it end and say:

![can t find input files](https://user-images.githubusercontent.com/13344308/36063370-b5239f8a-0e5a-11e8-8ac1-674639b5a1b3.png)

**Comment by 1adrianb** [comment]
No, it looks that they are beloning to a third party library and as such I am not aware about their content. 

The second error that you report is unrelated to the code from here, since such file is not present in this repository. It looks however than no input was provided to your script. If this error persists i suggest to contact the original author of the code you are trying to run.

**Comment by ZeroCool22** [comment]
DFAKER suggested me:

> Try deleting the downloaded FAN network from C:\Users%USERNAME%\AppData\Local\face_alignment\data other than that I have nothing to suggest, this is all inside the face_alignment library.

But it when it try to download it again, say that can't find the INPUT FILES:

![can t find input files](https://user-images.githubusercontent.com/13344308/36063415-5035595a-0e5b-11e8-96bc-8137ffd4a31d.png)

**Comment by 1adrianb** [comment]
@ZeroCool22 Again, this error is not relevant to the code from here. The advice that DFAKER gave to you was with respect to your first error and its suggestion was a valid one.

**Comment by ZeroCool22** [comment]
Can CLOSE this ISSUE, all this was because the pics weere in **PNG** format, need to be in **JPG**, lol.

Thx for answer me and try to help me, very handsome. :)

**Comment by 1adrianb** [comment]
@ZeroCool22 No worries, I am glad that you sorted it out.
