### ISSUE TITLE
Is it possible to get face part information from landmarks ? 

### ISSUE THREAD

**Issue by Skorkmaz88** [1adrianb/face-alignment#52]
Hi, is it possible to find landmark that belong to lips or eyes for example ?

**Comment by 1adrianb** [comment]
Hi @Skorkmaz88 ,
Yes, they are ordered. You can find the order of them here: https://ibug.doc.ic.ac.uk/resources/300-W/ in Figure 1.

**Comment by Skorkmaz88** [comment]
Thanks!
