### ISSUE TITLE
I made port 2DFan-4 to Keras.

### ISSUE THREAD

**Issue by iperov** [1adrianb/face-alignment#53]
it works x2 faster than pytorch, but initialization takes 20secs

if interested:
https://github.com/deepfakes/faceswap/tree/master/lib/FaceLandmarksExtractor

**Comment by Edwardmark** [comment]
@iperov is the website changed? I cannot open it.

**Comment by iperov** [comment]
@Edwardmark https://github.com/iperov/DeepFaceLab

**Comment by Edwardmark** [comment]
@iperov Thanks.

**Comment by Edwardmark** [comment]
@iperov Could you please tell me where your FAN code is, sorry, I cannot find them.

**Comment by iperov** [comment]
facelandmarksextractor
