### ISSUE TITLE
import face_alignment

### ISSUE THREAD

**Issue by pling0807** [1adrianb/face-alignment#59]
Hi ! I got an error: 
Traceback (most recent call last):
  File "/home/pi/face-alignment/test/facealignment_test.py", line 2, in <module>
    import face_alignment
ImportError: No module named 'face_alignment'

I have already copy the face_alignment file to the path(/usr/lib) but still get this error. 
Thank you for your helps... im just start with my pi3.

**Comment by taesung89** [comment]
It looks like an issue unrelated to the implementation of face_alignment. It's probably because the package face_alignment was not properly installed to your python. 
Did you install by calling python setup.py install?

**Comment by Meaad96s** [comment]
I did the 
pip install -r requirements.txt
python setup.py install
but still i get the same error!
