### ISSUE TITLE
Cannot download the model?

### ISSUE THREAD

**Issue by jaysimon** [1adrianb/face-alignment#62]
When I'm trying the example, I got something below, I suspect it cannot download the model, could you add a link of model?
```
hw@hw-work:~/workspace/02_work/52-face-aligment/examples$ python detect_landmarks_in_image.py
Traceback (most recent call last):
  File "detect_landmarks_in_image.py", line 8, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=False, flip_input=False)
  File "build/bdist.linux-x86_64/egg/face_alignment/api.py", line 106, in __init__
  File "/home/hw/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/hw/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 410, in _load
    magic_number = pickle_module.load(f)
cPickle.UnpicklingError: invalid load key, '<'.
```

**Comment by 1adrianb** [comment]
If the download was somehow interrupted you can clear the models using face_alignment.remove_models() and then try again. Thanks!

**Comment by leepand** [comment]
the same problem, and I used face_alignment.remove_models() , and got the following info:
>>> import face_alignment
>>> face_alignment.remove_models()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'remove_models'

**Comment by 1adrianb** [comment]
@leepand you need to first to create the object:
```
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=False, flip_input=False)
fa..remove_models()
```

**Comment by leepand** [comment]
@1adrianb thank you for quick response ,when do this then got the following info:
>>> import face_alignment
>>> fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=False, flip_input=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.7-x86_64/egg/face_alignment/api.py", line 106, in __init__
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 384, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: unexpected EOF. The file might be corrupted.
>>> fa.remove_models()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fa' is not defined

**Comment by 1adrianb** [comment]
@leepand please try to clone the repository again and resintall it. Afterward please remove this folder: {path_to_home}/.face_alignment

**Comment by Edwardmark** [comment]
I met the same problem, any clues@leepand@1adrianb

**Comment by 1adrianb** [comment]
@Edwardmark can you please try the suggestion from my last comment? Can you access my website however? If not I will try to upload the models to onedrive.

**Comment by Edwardmark** [comment]
@1adrianb I cannot access you website, I donnot know why. Thanks for your reply.

**Comment by 1adrianb** [comment]
Try to download from here: https://uniofnottm-my.sharepoint.com/:f:/g/personal/adrian_bulat_nottingham_ac_uk/Ev4KqgFQ5ENLsoy_plCiSLQBH-lxaoPLINqpNuSrhYcm8w?e=WnvCaW and then move the .tar files to {path_to_home}/.face_alignment

**Comment by Edwardmark** [comment]
@1adrianb Thanks, should I remove anything in the hidden file . or .. ?

**Comment by Edwardmark** [comment]
@1adrianb  I am sorry for so much questions, but there is not a directory named .face_alignment?should I create it?

**Comment by Code-Beast** [comment]
@1adrianb I can't find ./face_alignment in my home directory, do you know why?

**Comment by Edwardmark** [comment]
@Code-Beast just mkdir solved it

**Comment by jaysimon** [comment]
If you are Chinese, this model is easy to download as Thunder VIP, If you need ,I can help to upload to Baiduyun

**Comment by jaysimon** [comment]
this is the link of model, you can download and put them into ~/.facealigment/data
link：https://pan.baidu.com/s/15ap3uhfOA2hG8x9v3P13OA pw：84om

**Comment by ekinim** [comment]
When I import the face_alignment, it kills the kernel. What should I do? what may the problem be? Thanks for any help.
