### ISSUE TITLE
error with the append function

### ISSUE THREAD

**Issue by MTrac** [1adrianb/face-alignment#63]
thank you for that library. 

I get that error 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/face_alignment/api.py", line 225, in process_folder
TypeError: append() takes exactly one argument (2 given)

when I run 

>>> import face_alignment
>>> from skimage import io
>>> 
>>> fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, enable_cuda=True, flip_input=False)
>>> 
>>> preds = fa.process_folder('splitted', all_faces=True)

Is there any obvious reason ? 

Thank You for your time

**Comment by 1adrianb** [comment]
Sorry, it was an issue in the code. Please update to the last version and try again. Thanks
