### ISSUE TITLE
how to actually align faces?

### ISSUE THREAD

**Issue by Edwardmark** [1adrianb/face-alignment#66]
It seems that FAN can get the landmarks location, but do you know how to apply suitable affine transform to align the faces?

**Comment by 1adrianb** [comment]
Hi @rpyee, the computer vision community larger considers face alignment to be the task of localizing fiducial facial points on 2D images. As such the terms face alignment and points/landmarks localisations are used interchangeable. It is in general easy to remove the affine transformations based on the located fiducial points, as an example is applying a procrustes analysis.
