### ISSUE TITLE
Getting  Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by likwifi** [1adrianb/face-alignment#70]
Hi I'm getting following error
Getting  Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

any ideas why this may happen.
Environment: Ubuntu 14, python 2.7

**Comment by 1adrianb** [comment]
@likwifi Unfortunatelly I do not know exactly what is causing the issue, since I never encoutered it before, but it is most likely related either your setup or the pytorch version used. Try searching "pytorch" + your_error_message
