### ISSUE TITLE
how to use video face alignment?

### ISSUE THREAD

**Issue by buyi1128** [1adrianb/face-alignment#71]
In video face alignment, the processing time of each frame is more than one second  using python in my PC, but the video example showed in github is so fast. So why?  My processor of PC is i-7 with 16G memory.

**Comment by 1adrianb** [comment]
@buyi1128 The video provided was generated on a GPU and as such it is unlikely that you will be able to achieve real-time without one. In addition to this, the face detection is probably the slowest part, as such you may need to run a face detector apriori.

**Comment by TDBTECHNO** [comment]
can i get the code to process it on video?

**Comment by seva100** [comment]
@TDBTECHNO feel free to use this video2video script: https://gist.github.com/seva100/71807a726d2d153d5b5a30773999ebd6
