### ISSUE TITLE
Using model on iOS

### ISSUE THREAD

**Issue by Onotoko** [1adrianb/face-alignment#79]
Hi,
Please let me know, that your model can use on iOS?
Thanks!

**Comment by 1adrianb** [comment]
Hi @hanoi2018,

Not dirrectly unfortunatelly. However you can probably export the model using onnx https://github.com/onnx/onnx

**Comment by hanoi2018** [comment]
Thank @1adrianb, so I can export to onnx then coreml? And sorry I do not know exactly this model need face detection first or not?
