### ISSUE TITLE
Problem with CUDA 9.0

### ISSUE THREAD

**Issue by qingguoxu** [1adrianb/face-alignment#81]
I use pytorch 0.4 and cuda 9.0. Everything is fine except when I import face_alignment, it cannot find libcusolver.so.8.0 while import dlib. In the requirements.txt, the dlib version is 19.5.0. I guess this version is built with CUDA 8. 

I just "pip uninstall dlib" and reinstall a latest one with "pip install dlib". Then the dlib is upgraded to 19.13.1, which support CUDA 9. Then everything is fine.

**Comment by 1adrianb** [comment]
@qingguoxu Thanks for catching this!
