### ISSUE TITLE
Why I cannot visit the homepage since 25th, Jun?

### ISSUE THREAD

**Issue by esdream** [1adrianb/face-alignment#82]
Hello Adrian,

Thanks for your sharing. I visited your hompage https://www.adrianbulat.com/face-alignment/ on 23th, Jun and taked an interest in it. However, when I try to visit it on 25th Jun, it failed. I also fail to run the code because it cannot download the face alignment depth network (FAN-D).

Can you help me to solve it? Thank you in advance.

**Comment by 1adrianb** [comment]
Hi,

I am sorry that you are encountering this issue. However the website is and was continuously available. If you are behind the great chinease firewall maybe this is what is causing the issue. Someone uploaded the models on Baidu drive, check the previous issues please and you should be able to use it to download them manually.

Thanks,
Adrian
