### ISSUE TITLE
face_alignment.FaceAlignment got an unknown error

### ISSUE THREAD

**Issue by visonpon** [1adrianb/face-alignment#84]
when i execute the command below, i got an unknown error:
`pred= face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, enable_cuda=True, flip_input= False).get_landmarks(x)`

RuntimeError: Error while calling cudaMallocHost(&data, new_size*sizeof(float)) in file /tmp/pip-build-_n7xryvl/dlib/dlib/dnn/gpu_data.cpp:185. code: 30, reason: unknown error.

Anyone can give some advice? thanks~

**Comment by 1adrianb** [comment]
@visonpon This error is caused by dlib. You can either run the face detector in cpu mode or contact the original authors of dlib.
