### ISSUE TITLE
What's the difference between outputs from torch and pytorch?

### ISSUE THREAD

**Issue by leeeeeeo** [1adrianb/face-alignment#87]
@1adrianb Hello, I tried both torch and pytorch.
1. When using torch, it came error at 22nd line in [https://github.com/1adrianb/2D-and-3D-face-alignment/blob/master/facedetection_dlib.lua](facedetection_dlib.lua).
![image](https://user-images.githubusercontent.com/25877709/42992149-550290a8-8c3a-11e8-9bf3-a6c24cf223b8.png)
So, I have no clue about its output.
2. Then I tried pytorch version, and it worked!
It outputs a numpy array (68,2) or (68,3)
So, I'm wondering what's the difference between outputs from torch and pytorch? Cause I don't know what's the output from torch is ...

**Comment by 1adrianb** [comment]
Hi @leeeeeeo,

If you are still having issues with the torch version please try the docker image wich should have everything pre-configured for you.

There a few more models available in torch, some of them will produce more accurate points when compared with the ones from pytorch.

**Comment by leeeeeeo** [comment]
@1adrianb Thank you !
