### ISSUE TITLE
Is there any way to download the FAN and FAN-D before using them in a script?

### ISSUE THREAD

**Issue by IAmSuyogJadhav** [1adrianb/face-alignment#92]
When I run
```python
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, enable_cuda=False, flip_input=False)
```
, it downloads the models for the first time and takes quite a while. Is there any way I can skip this? 
Like manually downloading the required files and putting them in a specified folder?

**Comment by 1adrianb** [comment]
Hi @IAmSuyogJadhav,

Yes, you can. 
Download links:
https://www.adrianbulat.com/downloads/python-fan/2DFAN-4.pth.tar
https://www.adrianbulat.com/downloads/python-fan/3DFAN-4.pth.tar
https://www.adrianbulat.com/downloads/python-fan/depth.pth.tar

You can copy there in your home folder in .face_alignment folder (You can also check your existing installation just to be sure, its hidden by default).

**Comment by IAmSuyogJadhav** [comment]
Thanks! Got it✌️

**Comment by ashafaei** [comment]
@visonpon The files are not tar archives. You should open them directly inside PyTorch
```python
import torch
data = torch.load('2DFAN-4.pth.tar')
```
I don't know why `.pth.tar` is chosen. It should be `.pth`.

**Comment by visonpon** [comment]
thanks~ @ashafaei i haved solved this error as you adviced.

**Comment by enerai** [comment]
Let me a conclusion that how we can download the model files in advance and load them. After you use `pip install face-alignment` install the face-alignment package `1.0.0`, the default face-alignment data directory is `/root/.face_alignment/data` if you are using the root in a docker. In general, you can use `cd ~ && pwd` to check the detailed user data directory, and the directory where you should put per-trained model files will be `[user_data_dir]/.face_alignment/data`

The necessary model files are as follows:
```
https://www.adrianbulat.com/downloads/python-fan/2DFAN-4.pth.tar
https://www.adrianbulat.com/downloads/python-fan/3DFAN-4.pth.tar
https://www.adrianbulat.com/downloads/python-fan/depth.pth.tar
https://www.adrianbulat.com/downloads/python-fan/s3fd_convert.pth
```

**Comment by jinfagang** [comment]
Sounds good。
