### ISSUE TITLE
What is the best and most accurate model?

### ISSUE THREAD

**Issue by Edwardmark** [1adrianb/face-alignment#94]
@1adrianb Hi, which model is best until now, I test the pytorch model, it seems not satisfactory. So I want to test the best model you provided, can you give me a link or sth?

**Comment by 1adrianb** [comment]
Hi @Edwardmark, the best models are available https://github.com/1adrianb/2D-and-3D-face-alignment , however I have not converted all of them to pytorch.
Regarding the face detector, dlib will not work for profile faces, it will either miss them (most likely) or provide a very poor bounding box. Dlib was provided here for simiplicty and it will result in general in sub-par performance.

**Comment by Edwardmark** [comment]
@1adrianb Is the pytorch version much worse than the torch ones? And could provide a download link to your model? I cannot access your website for firewall reason. Thanks.

**Comment by AlexD123123** [comment]
Hi Adrian, 

I wanted to run the python models, but it seems that only the torch models are supplied. Is it possible for you to supply a link to the pytorch model?

Thanks a lot, 
Alex

**Comment by 1adrianb** [comment]
Hi @AlexD123123 , I am afraid that I don't curently have the same torch models available in pytorch. The pytorch version is using some slighly different ones. The performance should be better now compared with the last report anyway thanks to the integration of a better face detector (SFD) in the python code.

However, if you want to try the pytorch ones, this package will automacally download them on the first usage.
If for some reasons you want to download them manually all the links used can be find in the init function: 
https://github.com/1adrianb/face-alignment/blob/3750f83b4d7bf3f4ba6318e40a4292e1aeb241a4/face_alignment/api.py#L47
