### ISSUE TITLE
dlib's CNN face detection model performs worse than one from face-recognition-models

### ISSUE THREAD

**Issue by jeongyoonlee** [1adrianb/face-alignment#96]
Currently the code downloads dlib's CNN face detection model from `https://www.adrianbulat.com/downloads/dlib/mmod_human_face_detector.dat`. 

Although it is supposed to be the same as one from `face_recognition_models` at https://github.com/ageitgey/face_recognition_models/blob/master/face_recognition_models/models/mmod_human_face_detector.dat, the one downloaded by this repo performs a lot worse than the one from `face_recognition_models`.

When tested with 1,000 images with one face in each image, `face-alignment` failed to detect faces from 363 images while `face_recognition` failed to detect faces from only 175 images.

Could you update `mmod_human_face_detecctor.dat` with latest version or the one from `face_recognition_models`?

**Comment by 1adrianb** [comment]
Hi @jeongyoonlee,

Thanks a lot for the finding! I have replaced the model with the new one as suggested. 
However, for best results I recomend something like: https://github.com/clcarwin/SFD_pytorch

Thanks a lot!

**Comment by jeongyoonlee** [comment]
You're welcome and thanks for the recommendation, @1adrianb. I will check it out. :)
